export const WORDS = [
  "ABODE", "BLISS", "CHUNK", "DEALT", "ELITE", "FLAIR", "GLOAT", "HEIST", "INPUT", "JOLLY",
  "KNEEL", "LEAPT", "MOIST", "NIGHT", "OPINE", "PROUD", "QUIRK", "ROAST", "SLUMP", "TRAIT",
  "URBAN", "VIVID", "WATCH", "XENON", "YACHT", "ZONAL", "AMPLE", "BRAWL", "CRISP", "DRAPE",
  "EXCEL", "FRONT", "GRIPE", "HOARD", "ISSUE", "JUMBO", "KNACK", "LUMEN", "MIRTH", "NUDGE",
  "OVARY", "PHASE", "QUEST", "RIDGE", "SWIFT", "TOWER", "UPEND", "VOWEL", "WREAK", "YEARN",
  "ZESTY", "ALERT", "BENCH", "CIVIL", "DODGE", "EPOCH", "FLOCK", "GLYPH", "HUMUS", "INBOX",
  "JOUST", "KARMA", "LOTTO", "MOUND", "NANNY", "OLDEN", "PAUSE", "QUOTA", "RENEW", "SCALP",
  "THORN", "USHER", "VALUE", "WEDGE", "XYLEM", "YOUNG", "ZIPPY", "ADAPT", "BRISK", "CHILL",
  "DRAFT", "ENACT", "FEIGN", "GRILL", "HOVEL", "IRONY", "JOKER", "KNEAD", "LOFTY", "MERCY",
  "NOBLE", "OPIUM", "PLUCK", "QUILL", "ROBIN", "SPADE", "TRACE", "ULTRA", "VAPID", "WEARY",
  "XEROX", "YIELD", "ZEBRA", "AGENT", "BLURB", "CRANE", "DRIVE", "EVOKE", "FLINT", "GUSTO",
  "HAVOC", "INERT", "JUMPS", "KIOSK", "LEMON", "MAXIM", "NOTCH", "OUTDO", "PRUNE", "QUICK",
  "REACT", "SHAKE", "TWINE", "UNZIP", "VISTA", "WRUNG", "XENIA", "YUCKY", "ZONED", "ABYSS",
  "BINGO", "CHIEF", "DECOY", "ELUDE", "FRESH", "GHOUL", "HAPPY", "IMPLY", "JEWEL", "KNOLL",
  "LINEN", "MOTTO", "NAIVE", "OVERT", "PULSE", "QUEST", "RUSTY", "SLATE", "TITLE", "USUAL",
  "VISIT", "WHILE", "VENOM", "YEAST", "ZAPPY"
];
